const fs = require("fs");
const path = require("path");

const {
    EmbedBuilder,
    ActionRowBuilder,
    ButtonBuilder,
    ButtonStyle
} = require("discord.js");

const {
    APPLICATION_RESULTS_CHANNEL
} = require("../config");

const applications = require("./applicationData");

const applicationSessionsPath = path.join(
    __dirname,
    "../data/applicationSessions.json"
);

module.exports = async (client, message, args) => {

    /*
    ========================================
    PERMISSION
    ========================================
    */

    if (!message.member.permissions.has("Administrator")) {
        return message.reply("❌ You don't have permission.");
    }

    /*
    ========================================
    GET APPLICANT
    ========================================
    */

    const member = message.mentions.members.first();

    if (!member) {
        return message.reply(
            "Usage: `!testapplication @User staff`"
        );
    }

    /*
    ========================================
    GET APPLICATION TYPE
    ========================================
    */

    const type = args
        .map((arg) => arg.toLowerCase())
        .find((arg) => applications[arg]);

    if (!type) {
        return message.reply(
            "❌ Invalid application type.\n\n" +
            "Available types: `staff`, `police`, `fire`, `ems`, `dot`"
        );
    }

    const application = applications[type];

    /*
    ========================================
    CREATE FAKE ANSWERS
    ========================================
    */

    const fields = [
        ...(application.information || []),
        ...(application.questions || [])
    ];

    const answers = {};

    for (const field of fields) {
        answers[field.id] = "TEST APPLICATION ANSWER";
    }

    answers.discord_username = member.user.username;
    answers.roblox_username = "TestRobloxUser";
    answers.age = "19";
    answers.timezone = "CET";

    /*
    ========================================
    SAVE APPLICATION SESSION
    ========================================
    */

    let sessions = {};

    if (fs.existsSync(applicationSessionsPath)) {
        sessions = JSON.parse(
            fs.readFileSync(applicationSessionsPath, "utf8")
        );
    }

    sessions[member.id] = {
        type,
        answers,
        currentIndex: fields.length
    };

    fs.writeFileSync(
        applicationSessionsPath,
        JSON.stringify(sessions, null, 2)
    );

    /*
    ========================================
    FIND RESULTS CHANNEL
    ========================================
    */

    const resultsChannel = await client.channels
        .fetch(APPLICATION_RESULTS_CHANNEL)
        .catch(() => null);

    if (!resultsChannel) {
        return message.reply(
            "❌ The application results channel could not be found."
        );
    }

    /*
    ========================================
    CREATE RESULTS EMBED
    ========================================
    */

    const embed = new EmbedBuilder()
        .setColor(application.color)
        .setTitle(
            `${application.emoji} New ${application.name} Application`
        )
        .setDescription(
            `A new application has been submitted by ${member}.\n\n` +
            `👤 **Applicant Information**`
        )
        .addFields(
            {
                name: "Applicant",
                value: `${member}`,
                inline: true
            },
            {
                name: "Application",
                value: application.name,
                inline: true
            },
            {
                name: "Status",
                value: "🟡 **PENDING REVIEW**",
                inline: true
            },
            {
                name: "Test Application",
                value:
                    "⚠️ This is a test application generated by staff.",
            }
        )
        .setThumbnail(
            member.user.displayAvatarURL({
                size: 256
            })
        )
        .setFooter({
            text: "State Line Roleplay • Applications"
        })
        .setTimestamp();

    /*
    ========================================
    BUTTONS
    ========================================
    */

    const row = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
            .setCustomId(`application_review_${member.id}`)
            .setLabel("Review Application")
            .setEmoji("📝")
            .setStyle(ButtonStyle.Primary),

        new ButtonBuilder()
            .setCustomId(`application_accept_${member.id}`)
            .setLabel("Accept")
            .setEmoji("✅")
            .setStyle(ButtonStyle.Success),

        new ButtonBuilder()
            .setCustomId(`application_deny_${member.id}`)
            .setLabel("Deny")
            .setEmoji("❌")
            .setStyle(ButtonStyle.Danger)
    );

    /*
    ========================================
    SEND RESULTS MESSAGE
    ========================================
    */

    await resultsChannel.send({
        embeds: [embed],
        components: [row]
    });

    /*
    ========================================
    CONFIRM
    ========================================
    */

    return message.reply(
        `✅ **Test ${application.name} application created.**\n\n` +
        `👤 Applicant: ${member}\n` +
        `📋 Questions: **${fields.length}/${fields.length}**\n` +
        `✅ Application is marked as **complete**.\n\n` +
        `📨 A test application was posted in ${resultsChannel}.`
    );
};